name: 提交变更

on:
  push:
    branches-ignore:
      - master
      - renovate/*

jobs:
  feature:
    name: Feature
    runs-on: ubuntu-latest

    # runs-on: ${{ matrix.os }}

    # strategy:
    #   matrix:
    #     os:
    #       - ubuntu-latest
    #       - windows-latest
    #     node:
    #       - 10
    #       - 12

    steps:
      - name: 检出分支
        uses: actions/checkout@v2
        with:
          # fetch all history so changesets can generate full changelogs
          fetch-depth: 0

      - name: 搭建环境
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          # node-version: ${{ matrix.node }}

      - name: 安装依赖
        run: yarn --frozen-lockfile

      - name: 变更 PR
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
